name: Merge InterText Files On Push

on:
  push:
    branches: [ "main" ]

jobs:
  merge:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python 3.8
      uses: actions/setup-python@v3
      with:
        python-version: "3.8"
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip

    - name: Get Commit Message
      run: |
        commit_msg=${{ github.event.head_commit.message }}
        
        python .github/scripts/main.py $commit_msg

  
